# Generated by Django 4.2 on 2025-11-30 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_name', models.CharField(max_length=200)),
                ('helper_phone', models.CharField(max_length=32)),
                ('helper_district', models.CharField(max_length=100)),
                ('support_details', models.TextField()),
                ('preferred_areas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReliefCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('location_description', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('current_occupancy', models.IntegerField()),
                ('needs', models.TextField(blank=True, help_text='Comma separated list of needs')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SosRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('gps_location', models.CharField(blank=True, max_length=100)),
                ('water_level', models.CharField(blank=True, choices=[('none', 'No water'), ('ankle', 'Up to ankle'), ('knee', 'Knee level'), ('waist', 'Waist level'), ('chest', 'Above chest'), ('roof', 'At roof level')], max_length=16)),
                ('safe_hours', models.CharField(blank=True, max_length=100)),
                ('floor_level', models.CharField(blank=True, max_length=10)),
                ('additional_info', models.TextField(blank=True)),
                ('needs_food', models.BooleanField(default=False)),
                ('needs_medicine', models.BooleanField(default=False)),
                ('need_power', models.BooleanField(default=False)),
                ('need_water', models.BooleanField(default=False)),
                ('phone_battery_percentage', models.IntegerField(blank=True, max_length=8, null=True)),
                ('emergency_type', models.CharField(blank=True, choices=[('trapped_by_flood', 'Trapped by Flood'), ('evacuation_needed', 'Evacuation Needed'), ('medical_emergency', 'Medical Emergency'), ('landslide_risk', 'Landslide Risk'), ('landslide_occurred', 'Landslide Occurred'), ('other', 'Other')], max_length=32)),
                ('number_of_people', models.IntegerField(default=1)),
                ('has_children', models.BooleanField(default=False)),
                ('has_elderly', models.BooleanField(default=False)),
                ('has_disabled', models.BooleanField(default=False)),
                ('has_medical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='new', max_length=16)),
                ('internal_notes', models.TextField(blank=True)),
            ],
        ),
    ]
