# Generated by Django 4.2 on 2025-11-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefcamp',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reliefcamp',
            name='current_occupancy',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sosrequest',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sosrequest',
            name='phone_battery_percentage',
            field=models.PositiveIntegerField(blank=True, max_length=8, null=True),
        ),
    ]
