# Generated by Django 4.2 on 2025-11-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_alter_reliefcamp_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosrequest',
            name='phone_battery_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
